"""initial migration

Revision ID: 3b95836101b
Revises: None
Create Date: 2015-01-17 12:01:46.265953

"""

# revision identifiers, used by Alembic.
revision = '3b95836101b'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=150), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email')
    ### end Alembic commands ###
